FROM node:14.15

# Create app directory
EXPOSE 8081
WORKDIR /srv/www
USER root

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json ./
COPY package-lock.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
ADD dist .

EXPOSE 3000
CMD [ "npm", "run","start:dev" ]