name: CI Jest - Unit Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout (Copy) repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NestJS CLI
        run: npm install -g @nestjs/cli

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test